added UserData class with author
ITU-BDSA23-GROUP3/Chirp pull request #136
Opened 2023-11-18 09:59 UTC by Juules32

- makes it possible to perform actions without querying user each time

2023-11-18 18:56 UTC, NatalieClaraPetersen requested changes
userdata class seems redundant, but i like the other changes

2023-11-18 18:56 UTC, NatalieClaraPetersen commented on src/Chirp.Web/Pages/Auth.cshtml.cs
> +        _userData.Author = _authorRepository.FindAuthorsByName(userName ?? "").FirstOrDefault();
should be placed under _authorRepository.CreateAuthor(...) if hasn't been created yet

2023-11-18 18:58 UTC, NatalieClaraPetersen commented on src/Chirp.Web/Pages/TimelineModel.cshtml.cs
> +    public int GetUserId(string? authorName = null)
I changed this earlier in my own PR upon your request

2023-11-18 19:12 UTC, NatalieClaraPetersen commented on src/Chirp.Infrastructure/UserData.cs
> +public class UserData {
should contain some attributes but not an author object, otherwise it loses purpose and an author in auth.csthml.cs would suffice

2023-11-18 19:14 UTC, NatalieClaraPetersen commented on src/Chirp.Infrastructure/UserData.cs
> +public class UserData {
id, name, email

2023-11-19 02:01 UTC, Juules32 commented
Note to self: It is very hard to use UserAuthor as a shared field in authorRepository since is it used as Scoped, meaning the value doesn't always persist.

2023-11-19 02:01 UTC, closed without merging

2023-11-19 02:02 UTC, Juules32 commented
Note to self 2: the changes to RouteName here can still simplify the code.